const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');

router.get('/stats', adminController.getStats);
router.post('/users', adminController.createUser);
router.post('/users/bulk', adminController.bulkCreateUsers);
router.get('/users', adminController.listUsers);
router.delete('/users/:id', adminController.deleteUser);
router.post('/promote', adminController.promoteStudents);
router.get('/staff', adminController.listStaff);
router.get('/departments', adminController.listDepartments);
router.post('/departments', adminController.createDepartment);
router.put('/departments/:id', adminController.updateDepartment);
router.delete('/departments/:id', adminController.deleteDepartment);
router.get('/classes', adminController.listClasses);
router.post('/classes', adminController.createClass);
router.get('/classes/:id/students', adminController.getClassStudents);
router.put('/classes/:id', adminController.updateClass);
router.delete('/classes/:id', adminController.deleteClass);
router.get('/subjects', adminController.listSubjects);
router.post('/subjects', adminController.createSubject);
router.put('/subjects/:id', adminController.updateSubject);
router.delete('/subjects/:id', adminController.deleteSubject);
router.get('/timetable', adminController.getTimetable);
router.post('/timetable', adminController.upsertTimetable);
router.delete('/timetable/:classId', adminController.resetTimetable);
router.post('/assign-role', adminController.assignRole);
router.get('/staff-dashboard-data', adminController.getStaffDashboardData);
router.get('/attendance-sheet', adminController.getAttendanceSheet);
router.post('/mark-attendance', adminController.markAttendance);
router.get('/class-embeddings', adminController.getClassEmbeddings);
router.get('/subject-attendance', adminController.getSubjectAttendance);

module.exports = router;